### ISSUE TITLE
Support preview seekbar on TV

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#648] opened 2023-10-03 18:44 UTC
### Describe your suggested feature

I am assuming this might already be intended since it exists in TV layout, however it doesn't appear to work, I assume this might have to do with the fact you can't focus on the progress bar.

I was not sure if this is a feature or bug, so just went with feature since it is "adding" something. Feel free to correct me if I am wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment] 2023-10-03 18:48
It also doesn't work in trailers. That is not too important though but just noting it since the layout also seems to exist in trailers. Not sure of intent or not.

**Comment by LagradOst** [comment] 2023-10-03 19:19
> It also doesn't work in trailers. That is not too important though but just noting it since the layout also seems to exist in trailers. Not sure of intent or not.

trailers not showing is intended behavior

**Comment by LagradOst** [comment] 2023-10-03 19:21
tv not showing is simply because the behavior to do that needs to be manually added as seeking is not done with the seek bar on tv

**Comment by Luna712** [comment] 2023-10-05 05:36
> tv not showing is simply because the behavior to do that needs to be manually added as seeking is not done with the seek bar on tv

Yes I confirmed this by running Google TV in scrcpy, and dragging the slider the preview works fine. So I am not exactly sure how to do this, but I might try and work on it a bit. Honestly I think the seek functionality could do some work on TV, to make it a bit better without buffering, so you can hold down the keys, to fast forward, see previews, and select a frame without deeling with buffering a dozen times before you find the right spot, like with the Google TV app for example.

Though I will say I am //extremely// happy with the current implementation of the preview bar, and once again, thank you very much for finishing that up. It makes things much easier to seek on the phone anyway.

**Comment by Luna712** [comment] 2023-10-05 05:37
> tv not showing is simply because the behavior to do that needs to be manually added as seeking is not done with the seek bar on tv

@LagradOst 

Yes I confirmed this by running Google TV in scrcpy, and dragging the slider the preview works fine. So I am not exactly sure how to do this, but I might try and work on it a bit. Honestly I think the seek functionality could do some work on TV, to make it a bit better without buffering, so you can hold down the keys, to fast forward, see previews, and select a frame without deeling with buffering a dozen times before you find the right spot, like with the Google TV app for example.

Though I will say I am *extremely* happy with the current implementation of the preview bar, and once again, thank you very much for finishing that up. It makes things much easier to seek on the phone anyway.

**Comment by Luna712** [comment] 2023-10-10 16:12
I tried to work on this a bit but I could not figure this one out so I'll probably have to leave it to someone else.

**Comment by fire-light42** [comment] 2023-11-02 20:06
This will be closed as some TV devices simply does not support it and just crash due to low ram. https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/player/PreviewGenerator.kt#L65

**Closed by fire-light42** 2023-11-02 20:06 UTC
Labels: enhancement

**Comment by Luna712** [comment] 2023-11-02 22:10
> This will be closed as some TV devices simply does not support it and just crash due to low ram. https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/player/PreviewGenerator.kt#L65

@fire-light42 

Why can this just not be based off memory available?
like:
```kt
fun getAvailableMemory(context: Context): Long {
    val activityManager = context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
    val memoryInfo = ActivityManager.MemoryInfo()

    activityManager.getMemoryInfo(memoryInfo)
    // Available memory is in memoryInfo.availMem
    // Maybe we could use threshold here instead, not sure
    return memoryInfo.availMem // in bytes
}
```

This could reduce any potential issues, not require a setting, and still more reliable disable for TVs that do not support this due to memory

**Comment by Luna712** [comment] 2023-11-02 22:27
This is basically what I was thinking:
```kt
import android.app.ActivityManager

fun Context.getAvailableMemory(): Long {
    val activityManager = getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
    val memoryInfo = ActivityManager.MemoryInfo()

    activityManager.getMemoryInfo(memoryInfo)

    return memoryInfo.availMem
}

fun Context.isLowMemory(): Boolean {
    val availableMemory = getAvailableMemory()
    val thresholdBytes = 1L * 1024 * 1024 * 1024 // 1GB in bytes

    return availableMemory < thresholdBytes
}

// In PreviewGenerator
fun new(): IPreviewGenerator {
    /** disable if there is law RAM */
    return if (context.isLowMemory()) {
        empty()
    } else {
        PreviewGenerator()
    }
}
```

**Comment by Luna712** [comment] 2023-11-02 22:44
@Blatzar @fire-light42 does that seem like an acceptable solution to this or not still?

**Comment by fire-light42** [comment] 2023-11-02 23:29
@Luna712 that solution would only be accepted if we also had real UI for TV

**Comment by Luna712** [comment] 2023-11-02 23:38
> @Luna712 that solution would only be accepted if we also had real UI for TV

@fire-light42 

If that solution would be accepted I can try to make one work

**Comment by RokeJulianLockhart** [comment] 2023-11-04 00:18
> https://github.com/recloudstream/cloudstream/issues/648#issuecomment-1791466721

@fire-light42, that's “simply” wrong in my case - my TV has about 8 GiB of RAM, more than some smartphones. It can definitely support this.

**Comment by fire-light42** [comment] 2023-11-04 00:50
> @fire-light42, that's “simply” wrong in my case - my TV has about 8 GiB of RAM, more than some smartphones. It can definitely support this.

We had several crash reports on tvs after we enabled this feature by default. The average TV this app is running on does not have the capability of having this feature enabled by default. While yours might support it without issue, several simply could not use the app after this was introduced

**Comment by RokeJulianLockhart** [comment] 2023-11-04 00:51
> https://github.com/recloudstream/cloudstream/issues/648#issuecomment-1793275841

@fire-light42, so wouldn't adding a disabled-by-default toggle with a performance warning be adequate?
