### ISSUE TITLE
Trakt Support

### ISSUE THREAD

**Issue by owen-the-kid** [recloudstream/cloudstream#290] opened 2022-12-28 16:39 UTC
### Describe your suggested feature

it could be usefull if i could sync cloudstream on other devices or other apps like stremio or the kodi add-on the crew

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rollingmoai** [comment] 2023-01-19 09:12
Duplicate of #122

**Closed** 2023-01-31 09:48 UTC
Labels: duplicate, enhancement

**Comment by rokejulianlockhart** [comment] 2023-02-01 01:19
@rollingmoai, considering https://github.com/recloudstream/cloudstream/issues/122#issuecomment-1405487569, wouldn't tracking integration of such different services be beneficial?

Trakt's and kitsu's ways of tracking progress are fundamentally different, after all. Kitsu would barely be different to MAL and AniList, but Trakt is significantly more complex.

**Comment by rollingmoai** [comment] 2023-02-01 01:40
I'm guessing they want to merge it into one issue, so that's not on me.
