### ISSUE TITLE
Please add Webview 

### ISSUE THREAD

**Issue by ShoaibKhanali** [recloudstream/cloudstream#778] opened 2023-11-18 16:01 UTC
### Describe your suggested feature

Certainly! Think of a `WebView` as a window within your mobile app that brings the internet right to your users' fingertips. It's like having a small, built-in browser that allows your app to show web pages, videos, or interactive content without forcing users to leave your app's cozy environment. This creates a seamless experience, making it feel like your app and the web are holding hands, working together to provide a smooth and integrated journey for your users.

There is code in kotlin https://chat.openai.com/share/d97565ff-f6bc-41c3-989e-1753f5661fd7

### Other details

 A lot of extensions are required for the webview option to connect with the browser. 

![Screenshot_20231113-005017_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/143344199/1fd0a9ee-ef21-4daa-9b35-60e955dcfbce)

![Screenshot_20231029-233311_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/143344199/c81b2328-b2c3-4531-9fbf-4b5e37352d2d)

They are used to load links to reload. So many Aniyomi extensions are not working because of that. 

Uploading km_20231113-2_360p_30f_20231113_190713.mp4…

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ShoaibKhanali** [comment] 2023-11-18 16:16
https://github.com/recloudstream/cloudstream/assets/143344199/d3b82574-835c-441e-afaf-e884ab951eb0

**Comment by fire-light42** [comment] 2023-11-18 16:28
Holy fucking shit man, can you stop spamming useless requests. You even linked to chatgpt as that would help 💀 

Duplicate of 
https://github.com/recloudstream/cloudstream/issues/768
https://github.com/recloudstream/cloudstream/issues/766
https://github.com/recloudstream/cloudstream/issues/761
https://github.com/recloudstream/cloudstream/issues/759
https://github.com/recloudstream/cloudstream/issues/769

**Closed by fire-light42** 2023-11-18 16:28 UTC
Labels: enhancement, possible provider issue
