### ISSUE TITLE
Add a tracker: (TRAKT.TV)

### ISSUE THREAD

**Issue by MedRAM-RAM** [recloudstream/cloudstream#355] opened 2023-02-02 01:14 UTC
### Describe your suggested feature

It is better to add the tracking site TRAKT.TV, because it contains all the movies and series that are not found in Mal or AniList, thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment] 2023-02-02 08:23
duplicate of #122

**Closed** 2023-02-02 08:24 UTC
Labels: duplicate, enhancement

**Comment by rokejulianlockhart** [comment] 2023-02-14 19:18
@C10udburst, https://github.com/recloudstream/cloudstream/issues/122#issuecomment-1405487569?
