### ISSUE TITLE
Add proxy settings 

### ISSUE THREAD

**Issue by Parasgaming122** [recloudstream/cloudstream#952] opened 2024-02-26 10:28 UTC
### Describe your suggested feature

Many things are feo blocked I recently saw a app name Jhentai which had implemented this 
![Screenshot_20240226-152513](https://github.com/recloudstream/cloudstream/assets/98590880/d783b7fe-756a-43ac-8ec7-348316d55c51)
![Screenshot_20240226-152507](https://github.com/recloudstream/cloudstream/assets/98590880/08d04a82-d2bb-4278-b5cf-90a49c606198)
![Screenshot_20240226-152451](https://github.com/recloudstream/cloudstream/assets/98590880/25488b87-e9b2-41b1-9763-7d1627fd4a20)
So I was hoping you cloud add

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment] 2024-09-21 19:11
duplicate of #903

**Closed** 2024-09-21 19:11 UTC
Labels: duplicate, enhancement, possible duplicate
