### ISSUE TITLE
Play button doesn't currently show the next unwatched episode to play

### ISSUE THREAD

**Issue by LinkofHyrule89** [recloudstream/cloudstream#755] opened 2023-11-09 11:41 UTC
### Steps to reproduce

The play button always seems to just say Episode 1 and does not change to the current unwatched episode when one becomes available.

[Screenshot_20231109-043718](https://github.com/recloudstream/cloudstream/assets/3983279/9eae4acd-8c5e-430f-a5e1-93ad3f1b132e)

### Expected behavior

When an unwatched episode is available it should say that episode instead of episode 1. If you mark if so's watched or watch them manually it should offer the next unwatched episode on the play button.

!

### Actual behavior

Currently if there are multiple watched episodes The play button does not offer the next unwatched episode.

### Cloudstream version and commit hash

4.2.1 11136fe

### Android version

Android 10 (Sony Bravia Google TV)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment] 2023-11-10 17:42
Looks like it is caused by removeLastWatched being called when the last episode is seen. 

Possible to replicate using:

```kt
        val animeResponse = (loadResponse as AnimeLoadResponse)
        animeResponse.episodes = animeResponse.episodes.apply {
            this[DubStatus.Subbed] = this[DubStatus.Subbed]!!.subList(0,2)
        }
```
In postSuccessful in case anyone wants to replicate it.

**Comment by LinkofHyrule89** [comment] 2024-02-16 03:59
This bug still exist in the current latest nightly build are there any updates on this?

**Comment by KingLucius** [comment] 2024-03-15 13:36
Can you please check #983 if this fixed incase of actuall watching (still working on mark as watched button)

**Comment by LinkofHyrule89** [comment] 2024-03-16 10:02
It seems like of you wash and episode and it goes to the next episode and the episode is in the "Continue watching" it ahead of correctly. But if you mark an episode as watched or remove it from the continue watching it shows it as Episode 1 still. There is an edge case where if it's multiple sets of episodes it'll just start with the first episode of the season selected. So it seems like it's still pretty much broken in most cases. When there a be episode that's unwatched that gets added and the previous episode is watched it still shows episode 1 instead of that newest unwatched episode. I am on build 4.3.1 638cc4f.

**Comment by KingLucius** [comment] 2024-03-16 10:35
Ok i will check it more deep

**Comment by KingLucius** [comment] 2024-03-19 15:51
Can you please check #996

**Comment by LinkofHyrule89** [comment] 2024-03-20 12:06
Will test once it's merged into beta.

**Closed** 2024-03-25 00:05 UTC
Labels: bug

**Comment by LinkofHyrule89** [comment] 2024-03-25 08:41
It seems to be some what fixed, however it seems like the episodes on the list that are watched normally are counted differently than the ones that were marked as watched so you have to go back and mark things as watched. But definitely an improvement overall.

**Comment by KingLucius** [comment] 2024-03-25 14:45
Can you elaborate your notes about this as I am so curious to create a perfect behavior for this.

**Comment by fire-light42** [comment] 2024-03-25 16:34
> Can you elaborate your notes about this as I am so curious to create a perfect behavior for this.

This was what I was confused about, and why I blocked your PR at first. Reread my comments

**Comment by LinkofHyrule89** [comment] 2024-03-25 19:37
Basically even though an episode shows as watched in the episode list it might ignore it but after I click Mark as Watched it works correctly. Hopefully that makes sense it's a bit odd.

**Comment by fire-light42** [comment] 2024-03-25 23:05
> Basically even though an episode shows as watched in the episode list it might ignore it but after I click Mark as Watched it works correctly. Hopefully that makes sense it's a bit odd.

Ye, that exact problem was what I saw when reading the code and commented about, but assumed that kinglucius meant it to be that way.

**Comment by LinkofHyrule89** [comment] 2024-03-26 00:25
Oh ok I see! I'm sure you guys can figure it out but I'll say it's better than it was! I appreciate your hard work to fix the problem.

**Comment by KingLucius** [comment] 2024-03-26 02:43
Yes, now i know what Fire meant, ok i will work on it

**Comment by LinkofHyrule89** [comment] 2024-03-28 00:47
Is there another PR or will it get posted in this same thread?

**Comment by KingLucius** [comment] 2024-03-28 12:41
there will be another PR

**Comment by KingLucius** [comment] 2024-04-13 18:42
Can you please test after last pre update

**Comment by LinkofHyrule89** [comment] 2024-04-14 12:00
I won't fully know until a new episode for a show gets posted but so far it seems like it's working. I appreciate your hard work to fix this bug!

**Comment by LinkofHyrule89** [comment] 2024-04-14 12:19
Ok so I found that using the "Mark as Watched" feature no longer works for this. I think that watching an episode should also mark it as watched and both should be honored. Although currently it does appear when you watch an episode it will properly show the next episode on the play button.

**Comment by KingLucius** [comment] 2024-04-14 12:49
CS concept for "mark as watched" it's for manual watching.
Currently the button defaults to the episode after last 90% watched episode.

**Comment by KingLucius** [comment] 2024-04-14 16:20
You mean it should respects both cases ? Watched status and real watching ?

**Comment by fire-light42** [comment] 2024-04-14 21:56
> You mean it should respects both cases ? Watched status and real watching ?

getDisplayPosition does not take into account the manual watch state

**Comment by LinkofHyrule89** [comment] 2024-04-15 00:30
Yeah it should respect both I think. Although it seems like after the watch time hits the threshold it should mark it as watched if that makes sense.

**Comment by KingLucius** [comment] 2024-04-22 04:38
Please check the last update

**Comment by LinkofHyrule89** [comment] 2024-04-22 10:04
I do think it's working properly now rather you watch it normally or use the "Mark as watched" menu option it is showing the next episode after the last watched episode on the play button properly. However, one thing I noticed is when you menu click on episodes if you simply watched an episode it is not "Marked as watched" and if you use the "Remove from watched" option on items that are "Marked as watched" from the menu option it doesn't set the watched minutes back to zero. So two things should be added when you fully watch an episode the normal method it should be the same as using the option "Mark as watched" and when you use t he "Remove from watched" it should set the watched minutes back to zero as if you had never watched it at all. Once again thanks for your hard work! Hopefully this information helps improve the app a bit more.
