### ISSUE TITLE
9anime

### ISSUE THREAD

**Issue by iCeY3** [recloudstream/cloudstream#89] opened 2022-09-06 20:06 UTC
### Steps to reproduce

Error and no links

![Screenshot_20220906_230332_CloudStream Beta](https://user-images.githubusercontent.com/98146929/188728318-f4fbde9e-8f4a-4d97-8696-1932efbfb459.jpg)
![Screenshot_20220906_230342_CloudStream Beta](https://user-images.githubusercontent.com/98146929/188728325-9cb8e203-0a5a-42ed-9ead-5b6391341ed4.jpg)

### Expected behavior

.

### Actual behavior

.

### Cloudstream version and commit hash

Latest

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment] 2022-09-06 20:07
as the bot said no provider issues here

also

duplicate of recloudstream/cloudstream-extensions#10

**Closed by C10udburst** 2022-09-06 20:07 UTC
Labels: bug
