### ISSUE TITLE
Favorite sources

### ISSUE THREAD

**Issue by Zero1720** [recloudstream/cloudstream#366] opened 2023-02-11 04:19 UTC
### Describe your suggested feature

Let us star the sources we use often so we don't have to scroll and find them everytime 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Rayforest** [comment] 2023-02-11 09:14
I would love this feature too! Just like we have the option in settings --> player --> preferred watch quality it would be really helpful to have a preferred source in the player (maybe like 5 preferences in order of priority). But I think this feature would be quite complicated to add and I think it would even be not possible to add because different providers have different sources. 

The next best thing or maybe the better thing than having this preference feature is the ability of each providers to remember which sources we mostly select while watching movies on them, or in other terms selecting the source which is mostly used as default. Even this I think is too difficult to code or smth. So, whatever it be I'm sooooooo thankful to all the devs and supporters for making this app!! Idc if things are a little buggy or if I have to fiddle with the settings to get the best results or it may take 1 or 2 seconds more to select our preferred source each time... It doesn't matter! All that matters is that this app does not suddenly go away and leave us all in the dust. This is too good of an app for us to lose 🥹

**Comment by eightyy8** [comment] 2023-02-11 13:58
Duplicate of #225

**Closed** 2023-08-04 15:27 UTC
Labels: duplicate, enhancement
